- composer.json
> added laravel/framework 5.3 dependency

- README.md
Took me about a week of poking at this to figure out how to use L5-Swagger with Passport and the `CreateFreshApiToken` middleware. Hoping to save others a few steps.
> Add section to README.md

- composer.json
- config/l5-swagger.php
- phpunit.xml
- src/Generator.php
- src/Http/Controllers/SwaggerController.php
- tests/GeneratorTest.php
- tests/TestCase.php
This update should resolve #140 , resolve #69
> Add option to generate YAML documentation file as a copy

- src/Generator.php
- tests/storage/annotations/OpenApi/Anotations.php
- Last update on https://github.com/zircote/swagger-php changes  \Swagger namespace to \OpenApi
- Also annotations prefix changed from @OAS to @OA.
> [BUG_FIX] Changes  \Swagger namespace to \OpenApi

- src/Generator.php
Changed `swagger-lume` to `l5-swagger` to prevent OpenApi error
> Fixed Typo error

- src/helpers.php
> Fix swagger assets path gettering

- src/Http/Controllers/SwaggerController.php
> Add support for dumping yaml files

- src/Generator.php
- tests/GeneratorTest.php
Solve the issue #235. 
@DarkaOnLine Please help me review the PR. 
Thanks. :smile:
> Made the @OA\Server annotation be compatible with L5_SWAGGER_BASE_PATH environment variable

- src/Generator.php
I think we missed this from #216
> Use File facade for generator

- composer.json
Needed to update orchestra/testbench to new version to support Laravel 7. All tests seem to run
> Laravel 7 Compatibilty

- config/l5-swagger.php
- resources/views/index.blade.php
Persist authorization login after refresh browser by persist_authorization = true in config file
> feature-persist-authorization-after-refresh

- config/l5-swagger.php
- src/Generator.php
> Change processors parsing

- config/l5-swagger.php
added securityScheme for Sanctum authentication which is available in Laravel 8
> Added Sanctum Authentication to securitySchemes closes #318

- resources/views/index.blade.php
> Add deepLinking param to Swagger-ui template

- .github/workflows/test-config.yml
- Dockerfile
- src/Generator.php
- src/Http/Controllers/SwaggerAssetController.php
- src/Http/Controllers/SwaggerController.php
- src/SecurityDefinitions.php
- tests/ConsoleTest.php
- tests/GeneratorTest.php
- tests/SecurityDefinitionsTest.php
- tests/TestCase.php
> Maintenance 2022-03

- Dockerfile
- config/l5-swagger.php
- src/Generator.php
- tests/GeneratorTest.php
> Allow to change OpenApi spec version

- config/l5-swagger.php
- src/Generator.php
> Use local OpenApi spec default version constant

- .gitignore
- Dockerfile
- composer.json
- phpunit.xml
- src/Generator.php
- tests/ConfigFactoryTest.php
- tests/ConsoleTest.php
- tests/SecurityDefinitionsTest.php
> Laravel 10 support

- composer.json
> Add doctrine/annotations

- .github/workflows/test-config.yml
- Dockerfile
- composer.json
- phpunit.xml
> Add Laravel 11 support

- config/l5-swagger.php
It's a small thing but it was stressing me out.
> Multi-Line Comment Formatting

- src/Http/Controllers/SwaggerController.php
> fix undefined format_to_use_for_docs

- src/Generator.php
> Fix possible operator not supported for strings error

- README.md
The linked example was moved in https://github.com/zircote/swagger-php/pull/1702/files#diff-b4d68dc855d0f9476d3f2ee343853bd21bf82ea9960d0cf06661baa244439dd6
> Fix link to example
