src/Console/PublishAssetsCommand.php
src/Console/PublishConfigCommand.php
src/Console/PublishViewsCommand.php

See [this](https://github.com/laravel/framework/issues/9586).
Currently with this code on Laravel 5.1 you get a:
[ErrorException]
Invalid argument supplied for foreach()
Error due to it interpreting that tags as a string instead of an array. This forces it to make it an array and fixed the error.

Fixes for 5.1

---

src/Generator.php

Excluded directories were not being correctly passed to the $options of Swagger\scan()

Fixes excluded directories

---

resources/views/index.blade.php

This will fix the issue when one tries to use an OAuth header like 'Bearer [TOKEN]' which currently gets encoded like 'Bearer%20[TOKEN]'. This encoding should only be done in the case of type 'query'.

Only url encode apiKey if needed

---

config/l5-swagger.php
resources/views/index.blade.php
src/Http/Controllers/SwaggerController.php

Currently everything is always collapsed when going to the documentation. Setting this option can show it as a list ( or everything uncollapsed ) right away.

Make docExpansion configurable

---

resources/views/index.blade.php
src/helpers.php
tests/RoutesTest.php

In order to make  OAuth2 authorization in the Swagger UI work, the `oauth2RedirectUrl` parameter needs to be set correctly (which defaults to `localhost...`). Therefore the `oauth2-redirect.html` needs to be available.

Support for Oauth2 redirect (implicit/accessCode)

---

composer.json
src/Console/GenerateDocsCommand.php
src/Console/PublishCommand.php
src/Console/PublishConfigCommand.php
src/Console/PublishViewsCommand.php

* Replaced deprecated fire() calls with handle() in console commands.
* Upgraded dependency versions to match Laravel 5.5.
Fork with 5.5 support is working fine in my Laravel 5.5 project.

Upgrade for Laravel 5.5 support

---

README.md
composer.json

With this feature, no need to manually add `L5Swagger\L5SwaggerServiceProvider` in config file

Add package auto discovery feature in Laravel 5.5

---

.gitattributes

I noticed your package was a little bloated for production use.
This PR excludes all the unnecessary tests and associated developer service configuration files
which takes up less storage and uses less bandwidth on every `composer require`
Also note I did not `export-ignore` the `LICENSE` despite the fact it isn't strictly necessary to run the code,
because I always include the license even with a package library.

export ignore developer files for distribution

---

src/routes.php

Consider my configuration:
```php
/*
|--------------------------------------------------------------------------
| Route for accessing api documentation interface
|--------------------------------------------------------------------------
*/
'api' => 'api/v1',
/*
|--------------------------------------------------------------------------
| Route for accessing parsed swagger annotations.
|--------------------------------------------------------------------------
*/
'docs' => 'api/v1',
/*
|--------------------------------------------------------------------------
| File name of the generated json documentation file
|--------------------------------------------------------------------------
*/
'docs_json' => 'open-api-specification.json',
```
This serves the swagger-ui at `/api/v1`,
the json …

fix route precedence

---

composer.json

The required laravel version in the 5.5 package is wrong, therefore I cannot update vom 5.5.4 to 5.5.6 where OpenAPI 3.0 is enabled.

fix laravel version in composer.json

---

resources/views/index.blade.php

Change **additionalConfigUrl** to **configUrl** to match parameter name from SwaggerController.php
```
'configUrl'          => config('l5-swagger.additional_config_url'),
```
```
configUrl: {!! isset($additionalConfigUrl) ? '"' . $additionalConfigUrl . '"' : 'null' !!},
```

Fix to make additional_config_url works

---

src/Generator.php

I've just realized that new warning appeared. Please review proposed fix.

Fix: Method generateDocs has 26 lines of code (exceeds 25 allowed). Consider refactoring. 

---

src/SecurityDefinitions.php

Passes flags that match what swagger-php provides by default to json_encode() to ensure output is pretty-printed, even after adding security definitions. Previously the output was encoded as pretty-printed JSON, pulled back in, then re-encoded with no flags (and thus no newlines).
This will help anyone who'd rather not have a conflict on generated specs if they make any changes at all in e.g. two branches.

Fix OpenAPI JSON pretty-printing

---

src/Http/Controllers/SwaggerController.php

Currently, the OpenAPI file is only regenerated when accessing the Swagger UI route (SwaggerController::api).  Since I use ReDoc instead of Swagger UI, I still have to generate my docs manually after every change.  This simply moves the doc generation decision from the UI route to the openapi route.

Respect always_generate option when generating OpenAPI file

---

src/Http/Controllers/SwaggerController.php
src/L5SwaggerServiceProvider.php
src/routes.php

`Class 'Request' not found` exception was raised when accessing the documentation.
It looks that not having Facade namespace make this happen.
I guess it will be the same for `File` and `Response` so I did the same for it.
The problem occured on Laravel 5.8.31 with php 7.2

Fix Request class not found exception

---

src/Http/Controllers/SwaggerController.php

If we don't have permissions to write file to our docs directory we cant 
see that error, **but** when we use command to generate file it write only "Regenerating docs" and thats all.

Error log when throwing exception

---

composer.json
src/Generator.php
tests/GeneratorTest.php

According to [swagger-php](https://github.com/zircote/swagger-php/blob/master/src/Annotations/AbstractAnnotation.php#L241), it dumps into YAML with some flags. I tweaked the YAML Dumper and wrote an test case for checking the type.
Please take a look. If you have any concerns, please let me know.

Issue #245: make the Yaml generator generate an empty array

---

composer.json
src/Console/GenerateDocsCommand.php
src/Generator.php
src/Http/Controllers/SwaggerController.php
src/L5SwaggerFacade.php
src/L5SwaggerServiceProvider.php
tests/GeneratorTest.php
tests/SecurityDefinitionsTest.php
tests/TestCase.php

This PR uses the Service Provider to register de `Generator` and inject the config as dependency, this way we can create multiple instances of the `Generator` with different options, I'm hoping it'll help to solve this issue #149 
The `Generator` method `generateDocs()` is not static anymore, but I created a Facade as `L5Swagger ` so you can call `L5Swagger::generateDocs()`.

Generator use Dependency Injection

---

src/Generator.php

Better error description for handling creating a directory that's thrown on makeDirectory line when the directory already exists.

L5 swagger generator throwing laravel file error exception

---

src/Generator.php

Hello,
Thanks for the release of 8.x which provided the long waiting feature of generating multiple docs.
While working with 8.x found that when using the generate command with --all it generates only 1 documentation file. And if I specified the file other files gets deleted.
After a bit of investigation found that `Generator@generateDocs` is being called in the loop for each document which calls `Generator@prepareDirectory` each time causing deleting the directory before generating the next document.
Here's a PR with a quick fix hope it gets approved and merged soon

Fix generating multiple documentations

---

src/Http/Controllers/SwaggerController.php
tests/RoutesTest.php

This fixes internal server error caused by incorrect extension check for determining if a response should be JSON or YAML.
<details>
<summary>Exception stack</summary>
```
Undefined offset: 1 {"exception":"[object] (ErrorException(code: 0): Undefined offset: 1 at /var/www/html/vendor/darkaonline/l5-swagger/src/Http/Controllers/SwaggerController.php:39)
[stacktrace]
#0 /var/www/html/vendor/darkaonline/l5-swagger/src/Http/Controllers/SwaggerController.php(39): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 [internal function]: L5Swagger\\Http\\Controllers\\SwaggerController->docs()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatc …
```

Fix exception on docs file request without extension.

---

resources/views/index.blade.php

:bug: #304 Fixing bug on requestInterceptor. Cannot set property 'X-CSRF-TOKEN' of undefined
Swagger UI v3.32.0 change requestInterceptor to make it async https://github.com/swagger-api/swagger-ui/releases/tag/v3.32.0
Now we have to get the request headers from the parameter.
Regards.

:bug: #304 Fixing bug on requestInterceptor. Cannot set property 'X-CSRF-TOKEN' of undefined

---

.travis.yml
composer.json
config/l5-swagger.php
src/Http/Controllers/SwaggerController.php

This PR adds support for:
- PHP8
- Travis test for PHP8
- New configuration papram `format_to_use_for_docs` which allows set to `json` or `yaml` format to determine which documentation file to use in UI
closes #336, #345, #344

Allow PHP8 and add new config param

---

.travis.yml
composer.json

I made some small changes to get l5-swagger running with Laravel 6 on PHP 8.0
The changes are based on the changes made for php8 support in l5-swagger 7 and 8.

PHP8 support in l5-swagger v6

---

config/l5-swagger.php
src/Generator.php
src/GeneratorFactory.php

#358 
Here is an example of a custom schema query parameter processor which is badly needed for automation.
https://github.com/zircote/swagger-php/tree/master/Examples/schema-query-parameter-processor
E.g. in my case I want to add all model fields to resulting swagger files without describing them in comments by hands. I have too many tables and fields for manually creating comments. So this option is badly needed for me.

Allows addin scan options to OpenApi\scan call, badly needed to add custom query processors

---

src/Http/Controllers/SwaggerController.php
tests/RoutesTest.php

- fixes fatal when requested `$filePath` is invalid
If non-existing doc is requested (e.g. https://example.com/docs/foo), an uncaught exception could be raised during `File::get()` call.
Added a guard to prevent that.
- respect "generate_always" flag
I think this was introduced back in https://github.com/DarkaOnLine/L5-Swagger/pull/172, presumably before `generate_always` config param was added.
Imo with addition of `generate_always` this condition became slightly off - if user doesn't want the file to be generated on the fly (`generate_always=false`) l5-swagger shouldn't be ignoring that (by checking if `File::exists()`)

Fix fatal during docs generation/respect "generate_always" flag

---

config/l5-swagger.php
resources/views/index.blade.php

Add ui default parameters to config/l5-swagger.php base on [swagger ui documentation](https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/)

Add ui default to l5-swagger.php

---

.gitattributes

Optimizes the `.gitattributes` file to not export the `.github/` directory and the Docker files for local development. This ensures these files do not end up in the published Composer package.

Exclude development files from Composer packaging

---

config/l5-swagger.php
resources/views/index.blade.php

This PR adds new config option ```use_pkce_with_authorization_code_grant``` with default value set to false. 
This new parameter allows to authorize through Authorization Code Grant with PKCE, because if set to true, it enables swagger-ui option ```usePkceWithAuthorizationCodeGrant```. #485

Add PKCE config parameter

---

composer.json
src/Http/Controllers/SwaggerAssetController.php
tests/ConfigFactoryTest.php
tests/ConsoleTest.php
tests/SecurityDefinitionsTest.php

Fixes #546
CVE-2021-46708
The swagger-ui-dist package before 4.1.3 for Node.js could allow a remote attacker to hijack the clicking action of the victim. By persuading a victim to visit a malicious Web site, a remote attacker could exploit this vulnerability to hijack the victim's click actions and possibly launch further attacks against the victim.
https://nvd.nist.gov/vuln/detail/CVE-2021-46708

Use Swagger UI >= 4.1.3 due to CVE-2021-46708

---

composer.json

When installing a fresh laravel 10 project there is a dependency bug that can be fixed by enabling symphony in a 7.0 version.

Updating symphony version requirements to avoid dependency downgrade in Laravel 10

---

config/l5-swagger.php

From broken link:
> https://github.com/zircote/swagger-php/tree/master/Examples/schema-query-parameter-processor
To updated link:
> https://github.com/zircote/swagger-php/tree/master/Examples/processors/schema-query-parameter

Fix SchemaQueryParameter link

---

config/l5-swagger.php
src/Generator.php
src/L5SwaggerServiceProvider.php
tests/GeneratorTest.php
tests/storage/annotations/OpenApi/Products/L5SwaggerAnnotationsExampleProducts.php

Allow to pass processors configuration to [swagger-php](https://zircote.github.io/swagger-php/reference/processors.html#programmatically-with-php)
closes #590

Allow to pass processors configuration to swagger-php

---

config/l5-swagger.php

After a lot of hours trying, I found that there is a bug while someone try to set a custom path for swagger-ui assets.

Fix Bug of L5_SWAGGER_UI_ASSETS_PATH(.env) not working

---

resources/views/index.blade.php

In dark mode ,Path summary don't show .Actually it was show but background color and text color are same .

change summary text color for dark mode
